apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otlp-auth-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.165.0
      helm:
        valueFiles:
          - $values/manifests/otlp-auth-proxy/k8s-polaris-core/values.yaml
    - repoURL: https://github.com/monkescience/gitops-proxmox.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: clickstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - FailOnSharedResource=true
      - CreateNamespace=true
