persistence:
  enabled: true
  storageClassName: local-path
  size: 2Gi

initChownData:
  enabled: false

admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

plugins:
  - grafana-clickhouse-datasource

grafana.ini:
  server:
    root_url: "http://192.168.134.200/grafana"
    serve_from_sub_path: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: ClickStack
        type: grafana-clickhouse-datasource
        access: proxy
        isDefault: true
        jsonData:
          host: clickstack-clickhouse-clickhouse-headless.clickstack.svc.cluster.local
          port: 9000
          protocol: native
          username: app
          defaultDatabase: default
        secureJsonData:
          password: hyperdx

extraObjects:
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: grafana
    spec:
      parentRefs:
        - name: public
          namespace: istio-system
      rules:
        - matches:
            - path:
                type: Exact
                value: /grafana
          filters:
            - type: RequestRedirect
              requestRedirect:
                path:
                  type: ReplaceFullPath
                  replaceFullPath: /grafana/
                statusCode: 301
        - matches:
            - path:
                type: PathPrefix
                value: /grafana
          backendRefs:
            - name: grafana
              port: 80
