apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-polaris-core-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/monkescience/gitops-proxmox.git
    targetRevision: main
    path: apps/k8s-polaris-core/platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
