otelCollectorEndpoint: http://clickstack-otel-collector.clickstack.svc.cluster.local:4318
otelInsecure: true

otelAgent:
  ports:
    otlp:
      hostPort: null
    otlp-http:
      hostPort: null
    metrics:
      hostPort: null
    health-check:
      hostPort: null

presets:
  logsCollection:
    enabled: true
  hostMetrics:
    enabled: true
  kubeletMetrics:
    enabled: true
  clusterMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
