apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-polaris-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/monkescience/gitops-proxmox.git
    targetRevision: main
    path: apps/k8s-polaris-core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - FailOnSharedResource=true
